sleep_state:
    key: w
    options:
        - 'awake'
        - 'sleep'
        - unknown
spikes:
    key: s
    options:
        - 'yes'
        - 'no'
        - unknown
seizures:
    key: e
    options:
        - 'yes'
        - 'no'
        - unknown
slowing:
    key: f
    options:
        - 'yes'
        - 'no'
        - unknown
artifact:
    key: a
    options:
        - 'yes'
        - 'no'
        - unknown
