butterworth_filter:
  butterorder:
  - !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - i8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      AwAAAAAAAAA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AwAAAAAAAAA=
  filter_type:
  - - bandstop
  - - highpass
  freq_filter_array:
  - - 50
    - 60
  - - 1
  fs:
  - 512
  step_nums:
  - 2
  - 3
frequency_downsample:
  input_hz:
  - 1024
  output_hz:
  - 512
  step_nums:
  - 1
