leifborel: /Users/bjprager/Documents/GitHub/CNT-codehub/user_data/audits/LEIFBOREL/audit_data_main.csv
bsc: /Users/bjprager/Documents/GitHub/CNT-codehub/user_data/audits/BSC/audit_data_main.csv
habitat: /Users/bjprager/Documents/GitHub/CNT-codehub/user_data/audits/HABITAT/audit_data_main.csv
